working build
kapshn/FocusStartHomeworks pull request #1
Opened 2020-10-17 06:11 UTC by kapshn

Pull feature homework-1 to review

2020-10-17 06:51 UTC, korshunigor commented
Задание принято на проверку

2020-10-17 07:47 UTC, kapshn commented
Сделал весь функционал готово для ревью

2020-10-21 12:53 UTC, noreasonwhyiamhere requested changes

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/Car.swift
> +    case Sedan = 1, Limousine = 2, Coupe = 3, Hatchback = 4, Van = 5, DIYcar = 0
вообще можно сделать DIYcar первым (тогда вся нумерация как раз начнется с 0) и тогда можно будет не делать следующего:
`case Sedan = 1` и тд

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/Car.swift
> +    private var carNumber: String?
а почему опшинал часть пропертей?)

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/Car.swift
> +        return year ?? -1
интересное решение)) вот если бы year не был опшинал такого делать бы не пришлось
у тебя же в любом случаем без года объект Car не получится создать)

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/Car.swift
> +        return body
вроде можно return не писать когда в методе/пропертях сразу какое-то выражение возвращается 
вот ссылочка, где почитать https://github.com/apple/swift-evolution/blob/master/proposals/0255-omit-return.md

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    Cars[id].setYear(newYear: year)
а если к примеру в массиве будет 5 элементов и я обращусь по id = 5, что будет?)

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    var int1: Int = 0
интересный нейминг)) все-таки лучше давать более говорящие названия

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    print("Year         : ", year == -1 ? "-" : year,
вот тут не пришлось бы проверять на магическое число -1, если бы year или не опшинал был бы, либо как-то по-другому его отсутсвие проверялось

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    Cars.remove(at: id)
а если в массиве будет 3 элемента и я захочу удалить по id  = 3, что будет?)

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    let nCar = Car.init(year: year,
можно просто Car(тут все параметры)

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +            int1 = Int(str)!
как мне кажется юзер все-таки может взять и напечатать не циферку)
что тогда будет?

2020-10-21 12:53 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +        }
if let str = readLine(){
            int1 = Int(str)!
        }
вот этот блок много раз повторяется, в целом мб его в отельный метод внести, чтобы код не дублировать

2020-10-24 03:26 UTC, kapshn commented on FocusStartHomeworks/Car.swift
> +        return year ?? -1
а как тогда можно поступить? просто по условию задания год должен быть опциональным параметром, и нужно же что-то по дефолту вернуть. Мог бы сделать на прямую возможность обращения к параметру, но мне кажется это плохой вариант с точки зрения инкапсуляции

2020-10-24 03:27 UTC, kapshn commented on FocusStartHomeworks/Car.swift
> +    private var carNumber: String?
ну по заданию год и карнамбер должны быть опциональны

2020-10-24 03:29 UTC, kapshn commented on FocusStartHomeworks/Car.swift
> +        return body
спасибо, поменял

2020-10-24 03:35 UTC, kapshn commented on FocusStartHomeworks/main.swift
> +    var int1: Int = 0
переделал

2020-10-24 03:37 UTC, kapshn commented on FocusStartHomeworks/main.swift
> +    print("Year         : ", year == -1 ? "-" : year,
ну если по заданию year должно быть опшинал, как тогда лучше обрабатывать значение которого может не быть?

2020-10-24 04:26 UTC, kapshn commented on FocusStartHomeworks/main.swift
> +        }
вынес в отдельный метод

2020-10-24 04:27 UTC, kapshn commented on FocusStartHomeworks/main.swift
> +            int1 = Int(str)!
это нужно через try catch решать?

2020-10-24 04:32 UTC, kapshn commented on FocusStartHomeworks/main.swift
> +            int1 = Int(str)!
убрал форс анврап, вроде работает нормально теперь (в отдельной функции)

2020-10-24 04:34 UTC, kapshn commented on FocusStartHomeworks/main.swift
> +    let nCar = Car.init(year: year,
не совсем понял что вы имеете в виду. вы про перенос на другую строку? просто я это сделал для более лёгкого понимания

2020-10-24 04:34 UTC, kapshn commented on FocusStartHomeworks/main.swift
> +    Cars.remove(at: id)
исправил

2020-10-24 04:34 UTC, kapshn commented on FocusStartHomeworks/main.swift
> +    Cars[id].setYear(newYear: year)
исправил

2020-10-24 04:42 UTC, kapshn commented
Постарался исправить все замечания

2020-10-24 06:26 UTC, kapshn commented
пока не смотрите, я понял ошибку свою, исправлю вечером

2020-10-24 21:43 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/Car.swift
> +        return year ?? -1
ну как мне кажется можно возвращать тоже опшинал, а уже где-то при создании вьюмодели (сущности из которой вью будет строится) обрабатывать как-то отображение года если оно nil)

2020-10-24 21:44 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    print("Year         : ", year == -1 ? "-" : year,
выше в комменте отписала примерный вариант) но это как вариант

2020-10-24 21:44 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    let nCar = Car.init(year: year,
не, я про то, что можно .init не писать

2020-10-25 12:18 UTC, kapshn commented
вроде как постарался всё исправить, проверьте пожалуйста

2020-10-25 15:29 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    Cars[id].setYear(newYear: year)
не очень поняла как исправил

2020-10-25 15:29 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    default: break
крч не нравится что тут происходит, куча одинаковых проверок сложно понять что происходит
как мне кажется надо как-то на методы разделять
не оч когда в одном кейсе столько всего происходит

2020-10-25 15:29 UTC, noreasonwhyiamhere commented on FocusStartHomeworks/main.swift
> +    return Cars[id].getBody() == Body(rawValue: filterId) ? true : false
тут жеж опять по айди и без проверки

2024-08-07 13:01 UTC, closed without merging