ThreadSafeArray
kapshn/FocusStartHomeworks pull request #2
Opened 2020-10-25 11:45 UTC by kapshn

Выполнил задачу по созданию потокобезопасного массива

2020-10-26 09:36 UTC, korshunigor commented
Принято на проверку

2020-11-06 16:30 UTC, Jinfaa commented on FocusStartHomework-2/FocusStartHomework-2/ThreadSafeArray.swift
> +										attributes: .concurrent)
форматирование

2020-11-06 16:33 UTC, Jinfaa commented on FocusStartHomework-2/FocusStartHomework-2/ThreadSafeArray.swift
> +										attributes: .concurrent)
уровень доступа

2020-11-06 16:33 UTC, Jinfaa commented on FocusStartHomework-2/FocusStartHomework-2/ThreadSafeArray.swift
> +	var isEmpty: Bool {
уровень доступа

2020-11-06 16:34 UTC, Jinfaa commented on FocusStartHomework-2/FocusStartHomework-2/ThreadSafeArray.swift
> +		self.items.count
если будет добавление и считывание одновременно?

2020-11-06 16:36 UTC, Jinfaa commented on FocusStartHomework-2/FocusStartHomework-2/ThreadSafeArray.swift
> +		isolationQueue.async(flags: .barrier){
почему использовал async?

2020-11-06 16:37 UTC, Jinfaa commented on FocusStartHomework-2/FocusStartHomework-2/main.swift
> +DispatchQueue.global(qos: .userInteractive).async {
отдельную переменную let queue = DispatchQueue.global(qos: .userInteractive)

2020-11-06 16:39 UTC, Jinfaa commented on FocusStartHomework-2/FocusStartHomework-2/main.swift
> +let group = DispatchGroup()
DispatchGroup хорошо. 👍  
Можно было в данном случае sleep обойтись.

2020-11-06 16:40 UTC, Jinfaa commented on FocusStartHomework-2/FocusStartHomework-2/ThreadSafeArray.swift
> +		var item = self.items[0]
только на get? почему нет set?

2020-11-06 16:40 UTC, Jinfaa requested changes
Нужно немного доработать

2024-08-07 13:01 UTC, closed without merging